### ISSUE TITLE
RTCDataChannelInit structure pointers

### ISSUE THREAD

**Issue by Bogdan-D** [pions/webrtc#158]
https://github.com/pions/webrtc/blob/af2033741de289e3a1c36938da972fb16af2e1e2/rtcdatachannelinit.go#L5

Why do you have using pointers there? It's not very useful and makes things more complicated like from
```go
	id := uint16(1)
	neg := true
	max := uint16(1)
	peerConnection.CreateDataChannel("test", &webrtc.RTCDataChannelInit{ID: &id, Negotiated: &neg, MaxRetransmits: &max})
```
it could be simple
```go
	peerConnection.CreateDataChannel("test", &webrtc.RTCDataChannelInit{ID: 1, Negotiated: true, MaxRetransmits: 1})
```

**Comment by backkem** [comment]
Hi @Bogdan-D, The JavaScript API defines some defaults for the Init object. E.g.: the Ordered field should be 'true' by default. The fields are pointers so we can know if the user specified the value or if it wasn't set. E.g.: in your second example Ordered would default to 'false' since it was not specified and will be initiated with it's default value 'false'.

After much deliberation we decided to use pointers to solve this problem. We aim for it to be easy to follow examples written in JavaScript while working with pions/webrtc. We think this provides the behavior that most closely matches the JavaScript API.

We've also provided helpers to convert the values to pointer values in the null package. E.g.:
``` go
ordered := false
pc.CreateDataChannel("data", &webrtc.RTCDataChannelInit{
	Ordered: null.NewBool(ordered),
})
```
We should probably do a better job at documenting this.

Please let us know what you think of the approach. It has taken quite some discussion to get to this result but we may have to reconsider if real-world usage shows that the solution is not suitable.

**Comment by Bogdan-D** [comment]
Most common way I saw in golang community is to use constructor with setting default values for a struct.
Other way is to use maps. 
Well, in any case I understand the reason now

**Comment by Sean-Der** [comment]
@backkem @Bogdan-D 

I am going to close this (but feel free to re-open) I don't know if we made the right decision, but it hasn't come up since September so I don't think it is a blocking pain point.

If either of you disagree feel free to re-open and we can make a plan around what needs to change and when!

thanks
