### ISSUE TITLE
Improve SDP code so that we properly generate response

### ISSUE THREAD

**Issue by Sean-Der** [pions/webrtc#21]
Currently we statically set our supported codecs. This is incorrect.

As described in [section 5.3.1](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep#section-5.3.1)  of the JSEP spec: The SDP answer should contain a MediaDescription corresponding the each MediaDescription found in the SDP offer. If the PeerConnection can't comply with the MediaDescription in the offer, the media section should be marked as rejected by setting the port in the m= line to zero.

Examples
```
Offer Audio/Video -> Respond Audio/Video
Offer Audio -> Respond Audio
Offer Video -> Respond Video
``` 

**TODO**
- [ ] Improve SDP generation to support rejected a media section
- [ ] Adapt the SDP answer generation to match the offer.

**Comment by trivigy** [comment]
@Sean-Der I have been reading all of the RFCs and comparing them to what have been implemented so far and I feel like I might be ready to take a crack and this issue.

It seems that what this issue is asking for is better `Marshal` and `Unmarshal` for the entire `SessionDescription` struct. A lot of the stuff that RFC mentions is related to changing states and updating stuff inside of the Ice Agent. Being that `sdp` is its own package and does not access the ice agent. How should I go about doing that?

**Comment by trivigy** [comment]
I am assuming that the change will simply have to be made inside of `SetSessionDescription` to actually pass the IceAgent down to the unmarshalling and for now just create handles for things that might need to be manipulated inside of an IceAgent that was not implemented completely yet.

**Comment by trivigy** [comment]
@backkem Would love a little bit of guidance regarding whether I am thinking about this correctly.

**Comment by Sean-Der** [comment]
@trivigy Hey! Sorry for the radio silence when building this stuff, but it is all done now :)

I am gonna start an article on the Wiki for contributors about what you can do to get involved. I will send you a message on Slack when it is done.

----
This was implemented by https://github.com/pions/webrtc/commit/bf062e38b7b2c8108868cf6aea4b28279b074c32
