### ISSUE TITLE
RTP: Transport refactor

### ISSUE THREAD

**Issue by backkem** [pions/webrtc#272]
Refactor RTP as discussed on the [wiki](https://github.com/pions/webrtc/wiki/TransportDesign).
Current design can be found under [rtp-refactor](https://github.com/pions/webrtc/wiki/TransportDesign#rtp-refactor).

TODO:
* [x] [Optimizations](https://github.com/pions/webrtc/wiki/TransportDesign#optimizations)
* [ ] Separate [raw RTP](https://github.com/pions/webrtc/wiki/TransportDesign#raw-rtp).
* [ ] Move `internal/srtp` -> `github.com/pions/srtp`
* [ ] Move `pkg/rtp` -> `github.com/pions/rtp`
* [ ] Move `pkg/rtcp` -> `github.com/pions/rtcp`

**Comment by Sean-Der** [comment]
I will read the RFC, this sounds perfect as long as the mux/demux doesn't end up in `pions/dtls`!

This demuxing is very WebRTC centric, so might even be worth calling it `webrtc.Mux` or something along those lines since SRTP technically has nothing to do with DTLS (it just gets the encryption keys from it). But I fully support the design of linking transports.
```
                    +----------------+
                    |  127 < B < 192 -+--> forward to RTP
                    |                             |
packet -->  |     19 < B < 64  -+--> forward to DTLS
                    |                             |
                    |                B < 2   -+--> forward to STUN
                    +----------------+
```

**Comment by Sean-Der** [comment]
@backkem 

I started working on this, here are my thoughts and the steps I am going to take. Wanted to make sure I was on the right track.

----

[ ] Make the SRTP generic API generic. Just pass `[]byte` actually useful for public consumption
[ ] Move `internal/srtp` -> `github.com/pions/srtp`
[ ] Move `internal/sdp` -> `github.com/pions/sdp`
[ ] Move `pkg/rtp` -> `github.com/pions/rtp`
[ ] Move `pkg/rtcp` -> `github.com/pions/rtcp`
[ ] Create `internal/transport` and put SRTP wrapper in there (maybe not the right place)
[ ] Wire that all up!
-----

I don't think we should put any transport related abstractions around RTP/SRTP in the public API, we should keep that inside `webrtc`. The transport API makes sense for `SCTP` and `ICE` because those are real connections (reads/writes can happen internally etc..) but SRTP is just when people want to encrypt/decrypt blobs.

**Comment by backkem** [comment]
Seems like that wrapper may as well live in pions/srtp along side the contexts. Your choice thought. I guess I'm fine with leaving rt(c)p as is.

I just like how we can now throw a bunch of io.ReadWriteClosers together to form a stack on the data channel side. It seems rather powerful to mirror on the video side. You could conceivably start building a pipeline with decoders, filters, effects, ... .

**Comment by Sean-Der** [comment]
Just to follow up me and @backkem talked, and he is totally right here.

I am going to add `*Session` structs to `srtp` that allows us to follow the established pattern.
