### ISSUE TITLE
ORTC: Add ORTC data channel Constructors

### ISSUE THREAD

**Issue by backkem** [pions/webrtc#273]
This is a proposal to add the ORTC data channel related Constructors. In JavaScript this API looks as follows:
```javascript
var gatherer = new RTCIceGatherer(options);
var ice = new RTCIceTransport(gatherer);
var dtls = new RTCDtlsTransport(ice, certs);

// Data
var sctp = new RTCSctpTransport(dtls);
var channel = new RTCDataChannel(sctp, parameters);
```
In Go this would probably look like:
```Go
gatherer := webrtc.NewRTCIceGatherer(options)
ice := webrtc.NewRTCIceTransport(gatherer)
dtls := webrtc.NewRTCDtlsTransport(ice, certs)


// Data
sctp := webrtc.NewRTCSctpTransport(dtls)
channel := webrtc.NewRTCDataChannel(sctp, parameters)
```
It seems harmless to expose this API alongside the existing WebRTC API. In addition, we can use these constructors to setup our networking stack in `RTCPeerConnection.SetRemoteDescription`. It seems easiest to keep these in the webrtc package since a lot of the objects used by ORTC are shared with WebRTC. After #272 is implemented our networking stack should be sufficiently composable to build out these ORTC constructors.

I suggest to use this ticket for initial discussion and progress tracking. We can ticket out the individual changes needed in separate tickets.

**Comment by Sean-Der** [comment]
I agree with this!

I see a lot of value in this because it makes it possible to use WebRTC without signaling. I have never thought about it before, but I think that could empower a lot of interesting situations. Especially for embedded devices people may want to hardcode values or only want a subset (SCTP + DTLS + ICE) for example.

If possible it would be great to move these out to their own package. Eventually `pions/webrtc` just provides the browser API and nothing more.

**Comment by backkem** [comment]
Moved to pions/ortc#1.

**Comment by backkem** [comment]
Reopened due to large overlap between ORTC and WebRTC.
