### ISSUE TITLE
Web client

### ISSUE THREAD

**Issue by gedw99** [pions/webrtc#29]
https://github.com/zserge/webview

It's a fantastic golang based webview for all desktops.
Very very light and we'll tested.

You can bundle any client side golang code running outside the webview too.

Quick start example:
https://github.com/zserge/webview/tree/master/examples/todo-go

On windows it uses the built in browser ( shtml or something) not the edge browser.

If you need edge browser let me know..

**Comment by gedw99** [comment]
Found it :)

https://github.com/asticode/go-astilectron

**Comment by Sean-Der** [comment]
Hey @gedw99 thanks for sharing these!

I would love to see an example of having a webview application that handles all the signaling/UI code. If you have time to work on this, feel free to re-open and I will do anything I can to help.

Otherwise will close for now and move this to the wiki.

thanks!
