### ISSUE TITLE
Create example loop application

### ISSUE THREAD

**Issue by Moisesbr** [pions/webrtc#356]
Hi guys,
I trying to make a loop application which receives an offer by WebSocket from the browser and create an answer, until here ok, the example below works,
but I see goroutine leak after second interaction, line 137 is printing number of goroutines,
Probably I using peer connection in the wrong way. Please, could you tell me the right path?

```go
//echo_websocket.go

```
https://gist.github.com/Moisesbr/bf78029fc803cab8d3b09aeee91e73ce

**Comment by backkem** [comment]
Hi @Moisesbr, Thanks for checking out pions/webrtc. It's a bit hard to fully grasp the behavior of your code since the PeerConnection is defined as a global variable. In general, an existing PeerConnection isn't really meant to be re-used for different connection. Normally, all go-routines should close after calling `RTCPeerConnection.Close()` (This may take a couple of milliseconds). I see this is commented out on L163. Maybe you had some troubles using it?

If this doesn't help, you can try to print the stacks of the go routines to further debug the problem. We have an example of this [here](https://github.com/pions/transport/blob/master/test/util.go#L18). Feel free to post them here so we can help with interpretations.

Sidenote: Our [RTCSessionDescription](https://github.com/pions/webrtc/blob/master/rtcsessiondescription.go#L8) can be marshaled to JSON directly. I hope to do the same for the ICE candidates in the future.

**Comment by Moisesbr** [comment]
Tks, @backkemI will try this new approach.
