### ISSUE TITLE
Hardcoded header in IVFWriter

### ISSUE THREAD

**Issue by kacperjurak** [pions/webrtc#471]
Hi,

Why header in IVFWriter is hardcoded? When i try to save a video from using examples, then the video is set to 640x480 with 30fps. Number of frames is set to 900, so the video is always 30 seconds long, even i record a shorter one. Recorded video is accelerated when open in desktop player.

Thanks

```
func (i *IVFWriter) writeHeader() error {
	header := make([]byte, 32)
	copy(header[0:], []byte("DKIF"))                // DKIF
	binary.LittleEndian.PutUint16(header[4:], 0)    // Version
	binary.LittleEndian.PutUint16(header[6:], 32)   // Header Size
	copy(header[8:], []byte("VP80"))                // FOURCC
	binary.LittleEndian.PutUint16(header[12:], 640) // Version
	binary.LittleEndian.PutUint16(header[14:], 480) // Header Size
	binary.LittleEndian.PutUint32(header[16:], 30)  // Framerate numerator
	binary.LittleEndian.PutUint32(header[20:], 1)   // Framerate Denominator
	binary.LittleEndian.PutUint32(header[24:], 900) // Frame count
	binary.LittleEndian.PutUint32(header[28:], 0)   // Unused

	_, err := i.stream.Write(header)
	return err
}
```

**Comment by Sean-Der** [comment]
Hey @kacperjurak 

The `IVFWriter` atm is really just a quick hack so we can write to disk, I would love a PR to improve it some more! Maybe when you call `Close()` it will finalize the header values.

Right now it is hard to fill in a lot of detail since we are dealing with live video, and things like resolution are impossible to fill in. The resolution can change at anytime during the stream.

**Comment by Sean-Der** [comment]
@kacperjurak 

master has been updated to count the number of frames written, does this fix the playback speed for you? Also note that you need to refresh/close the tab for the file to finish writing (otherwise we write a temporary header)

Please re-open if you are still have issues! thanks for using pion :)

cc: @Antonito who did all the work here!

thanks!
