### ISSUE TITLE
SFU: new sfu example with websocket

### ISSUE THREAD

**Issue by adwpc** [pions/webrtc#507]
I'm writing sfu example with websocket, support video and audio. easy to use.

**Comment by nosovk** [comment]
Will be nice to have, because I wasn't able to run current SFU live, after a minute or two streaming stops, also TURN server not implemented in it, making it not very useful.

**Comment by Sean-Der** [comment]
Fantastic work @adwpc 

I added a few comments/questions to your PR but I think this would be a great thing to merge :) I think it might even be worth deleting the other SFU example, and just having this one be the default? It sounds like people find it more frustrating then useful?

@mjmac @maxhawkins @wdouglass what do you think of getting rid of the current SFU example? As a video dev would you appreciate one that does websockets already, or would you find the large LOC frustrating?

---
Hey @nosovk 

Do you need TURN, or would TCP candidates work also? I think a lot of SFUs have TURN support because they don't implement ICE themselves (which we have)

**Comment by nosovk** [comment]
@Sean-Der I try to create video stream one to many, from Europe to the USA. It means that there should be no direct connections to the source, I use TURN like repeater service in another country to beat channel limitations. That's why TURN looks like an optimal solution.

**Comment by wdouglass** [comment]
I think having both examples side by side is fine... I'm personally not using or interested in websockets, but I'm sure an example of websocket signalling is really useful for someone. As long as we have a well documented index of examples, then we shouldn't worry about having too many. If that document doesn't exist, I'll volunteer to write it.

**Comment by mjmac** [comment]
I agree with @wdouglass: There is probably value in having "batteries included" SFU vs. DIY SFU examples. At some point we may need to whittle down the set of examples if we get too many, but that's a good problem to have, imo.

We might want to rename the other one to minimal-sfu or something like that.
