### ISSUE TITLE
RTPReceiver.Read() EOF behaviour

### ISSUE THREAD

**Issue by rob-deutsch** [pions/webrtc#511]
Perhaps I'm using the wrong pattern here, but I have a goroutine reading packets out of a `Track` and pumping them elsewhere.

At some point I will want to close the `PeerConnection`, and I think that the code below could signal this in two different ways to my goroutine:

1. The function will return `fmt.Errorf("RTPSender has been stopped")`
2. The function will return `err = EOF` from `r.rtcpReadStream.Read()`

https://github.com/pions/webrtc/blob/3426d00e2cda2eba9dfff3cb71be6ffda68d813c/rtpreceiver.go#L101-L108

Is my evaluation correct? Can this be done a different way such that I can more gracefully handle a `PeerConnection` being torn down?

**Comment by Sean-Der** [comment]
This *might* be wrong, but I think you should check the associated `PeerConnection` for its `ICEConnectionState` 

* `r.rtcpReadStream.Read(b)` could return a bunch of different errors in the future, so I wouldn't check an enum
* WebRTC API doesn't have a `closed` property or anything like that
* Looking around [this](https://stackoverflow.com/questions/21233828/detecting-that-the-peers-browser-was-closed-in-a-webrtc-videochat) seems like how people do it in the browser so I feel like we should follow the same pattern

I could totally be wrong here though @backkem this seem crazy wrong at all?

**Comment by orai-arturo** [comment]
The above link may not be 100% correct.  In our testing a Disconnect state is temporary.  The connection may come back and continue to function.  For that reason we check on Failed.

**Comment by backkem** [comment]
I did end up doing this for SCTP:
http://github.com/pions/sctp/blob/a43306d926b0aeaa717ac012d96271e309d69948/association.go#L820
This gives you a way to signal normal shutdown up the stack.

My thoughts:
- I think we should implement `onconnectionstatechange`. That's probably the best way to keep track of the PeerConnection state, not just the ICE state.
- Related:  ICEConnectionState = 'disconnected' is the best we've got right now but I think that state is recoverable. In the API ICEConnectionState = 'Failed' is the actual end state for ICE itself.
- We do still need to make sure the SRT(C)P Read methods return. Otherwise there is no good way to end the read loops.
- Picking `io.EOF` to signal 'normal shutdown' would make it easier on the user to handle closure.
- There may be other cases where we want to signal 'normal shutdown' other than closing the PeerConnection, e.g.: renegotiation. In that case using `io.EOF` could be useful as well.
- I think this probably as a relation to what we do with `pions/rtpengine`.

I'd say, overall I think `io.EOF` isn't a bad choice if we want to provide this.

**Comment by rob-deutsch** [comment]
So I've been uhm'ing and uhh'ing about this for a couple of days now, and I think it might be possible to tackle this from a different perspective.

My understanding is that `RTPReceiver.Read()` cannot block on a closed `RTPReceiver` `RTPReceiver.Close()` echoes down to the `RTPReceiver.rtpReadStream`.

Based on that, I think there is a potential race condition when in `RTPReceiver.Read()` when `RTPReceiver.Close()` is called at the same time. The error returned will either be `fmt.Errorf("RTPSender has been stopped")` or the error from `RTPReceiver.rtpReadStream.Read()`.

In light of that, should the check of `RTPReceiver.closed` be removed from `RTPReceiver.Read()` altogether? And the return value/error from `RTPReceiver.Read()` should be a direct return of `RTPReceiver.rtpReadStream.Read()`?

**Comment by rob-deutsch** [comment]
Just leaving this here for future reference:

This Internet Draft contains some useful information about RTP/RTCP closing of streams https://tools.ietf.org/html/draft-zeng-rtsp-end-of-stream-00 . Of course, in the context of WebRTC it needs to be considered alongside SDP. And in the context of current pions-webrtc it needs to be considered alongside the requirement that `RemoteDescription()` can only be set once.

**Comment by Sean-Der** [comment]
Hey @rob-deutsch 

I followed up on all your ideas here! Everything is now properly enumed (so we don't have the same operation returning different enums)

I also used `io.EOF` and `io.ErrClosedPipe` (hopefully) in the right places.
