### ISSUE TITLE
Move examples to a standalone project

### ISSUE THREAD

**Issue by jinleileiking** [pions/webrtc#516]
## Summary

Move examples to a standalone project

## Motivation

example modifies does not show in webrtc commits. Thas sucks.

**Comment by rob-deutsch** [comment]
A couple of thoughts:

1. The pro of taking it out of the commit logs is partly offset by the difficulty of keeping pions-webrtc and the examples in sync. Especially when things are moving fast.

2. I was recently surprised to learn that the gstreamer packages were moved to an `internal` directory. I think it is not good that other people can't use them. Those gstreamer packages were an important part of me building my first POC pions-webrtc app.

**Comment by backkem** [comment]
My thoughts from Slack:
- I wouldn't built all these (different signaling) separate examples. It doesn't really show off more capabilities of our tools and it kinda bloats our examples (which they already are).
- I would consider splitting the examples in two: basic examples just showing off the API (e.g.: 'data-channels') and more involved examples (the ones with external dependencies) (like 'janus-gateway'). I would consider moving the the latter out of tree.
- I would build out the pions/sfu (or just pions/mediaserver?) and add all of these as pluggable transports. (Instead of multiple signaling examples)

Regarding @rob-deutsch comments:
- we could build the examples as part of the pions/webrtc CI. All examples in the separate repo can have a go modules to pull in dependencies.
- While it may be convenient we really don't want anyone to rely on the packages that are now in examples/internal. If we want to provide this we should find a place where we can correctly maintain and support these capabilities.

**Comment by backkem** [comment]
Also, please make sure to keep the commit history when pulling things into a separate repo.

**Comment by Sean-Der** [comment]
Duped with #561
