### ISSUE TITLE
Improve OSX Gstreamer-send example

### ISSUE THREAD

**Issue by IvoPereira** [pions/webrtc#540]
I am trying to run the example of [GStreamer-send](https://github.com/pions/webrtc/tree/master/examples/gstreamer-send) in OSX but I am struggling to follow the mentioned docs.

The instructions for installing GStreamer in OSX are non-existent but I've managed to install it by using the [direct packages in their website](https://gstreamer.freedesktop.org/data/pkg/osx/1.15.2/). (If anyone stumbles upon this and struggles due GStreamer not finding libffi, use Homebrew to install it, then `locate libffi.pc` and append the pkgconfig to your PKG_CONFIG_PATH).

The other required step to get the example working would be to copy the session description generated from JSFiddle (I assume? It isn't much clear in the docs) and pipe it to _gstreamer-send_.

Somehow, this step is failing on my computer. I've assured that I've run the `go get github.com/pions/webrtc/examples/gstreamer-send` command first, but still I am not being able to proceed.

Is there anything I might be missing out?

Thanks for such an awesome project.

**Comment by IvoPereira** [comment]
Got it working.

Just needed to build with `go build` inside the package.

**Comment by Sean-Der** [comment]
Hey @IvoPereira thanks for using pion WebRTC and the positive feedback :)

This feedback is great! I will update the instructions for using `brew` and installing GStreamer. If there is anything you think isn't documented well I would love to hear about it, I am pretty biased because I wrote things so data from others is super helpful.

thanks!
