### ISSUE TITLE
Add IPv6 Support

### ISSUE THREAD

**Issue by shithappens2016** [pions/webrtc#85]
listen udp4: address 0000:0000:0000:000:0000:000:0000:0000:00000: too many colons in address

**Comment by Sean-Der** [comment]
Thanks for the bug report @shithappens2016 !

This is in progress, and will close it out when it lands in master

**Comment by trivigy** [comment]
@Sean-Der I can use `net/ipv6` just like the way you used `net/ipv4` right?! All I need to do is just add the collection of the appropriate ipv6 based local candidates?! Am I missing anything else here?

**Comment by Sean-Der** [comment]
Sounds right to me!

The ICEAgent just needs to keep IPv4/IPv6 candidates separated. That way you only ping v4 remote candidates with local v4 candidates etc..

These issues are showing up because STUN servers are returning IPv6 address (and then we are trying to communicate with them via IPv4) and there is nothing around that.

I would push this after your `Transport` refactor, I would land that change first

**Comment by jacobloveless** [comment]
HI @Sean-Der I wanted to see if there was anything I could do to help here or if you needed any testing done - we're actually blocked on this IPv6 bit but have a test setup ready to go.

**Comment by Sean-Der** [comment]
Hey @jacobloveless thanks for using pion-WebRTC!

We are refactoring/cleaning up for this right now! @backkem is leading this one, but in the process of cleaning up how we do ICE this should happen also. I would say ~2 weeks, just need to add extra data around candidates (so we know if they are IPv6 or v4)

thanks!

**Comment by Sean-Der** [comment]
Hey @jacobloveless sorry that took so long!

But in good news we have removed our OpenSSL dependency AND we have IPv6 support. So hopefully you get a chance to try it out! If you hit any bugs I am always available in our Slack channel.

thanks

**Comment by jacobloveless** [comment]
Rockstars!
